
- name: Install GlusterFS
  hosts: glusterfs
  become: true
  vars_files:
    - vars/default.yml
  tasks:
  - name: Running for {{ ansible_os_family }}
    include_tasks: tasks/install_{{ ansible_os_family }}.yml

- name: Create trusted pool
  hosts: glusterfs[0]
  become: true
  vars_files:
    - vars/default.yml
  tasks:
  - import_tasks: tasks/setup_glusterfs.yml

- name: Mount distributed volume
  hosts: glusterfs
  become: true
  vars_files:
    - vars/default.yml
  tasks:
  - import_tasks: tasks/mount_glusterfs.yml