
- name: Install GlusterFS
  hosts: glusterfs
  become: true
  vars_files:
    - vars/default.yml

  tasks:
  - name: Running for {{ ansible_os_family }}
    include_tasks: tasks/install_{{ ansible_os_family }}.yml

  - import_tasks: tasks/setup_firewall.yml

  - import_tasks: tasks/setup_glusterfs.yml
    when: groups['glusterfs'][0]