- name: Init manager
  hosts: swarm_manager
  become: true

  tasks:
  - import_tasks: tasks/setup_manager.yml

- name: Join workers
  hosts: swarm_workers
  become: true

  tasks:
  - import_tasks: tasks/setup_worker.yml
    vars:
      token: "{{ hostvars[groups['swarm_manager'][0]]['worker_token'].stdout }}"
      manager: "{{ hostvars[groups['swarm_manager'][0]]['ansible_default_ipv4']['address'] }}"