- name: Docker swarm init
  hosts: swarm_manager
  become: true
  gather_facts: False

  tasks:
   - name: Install python binding for firewalld
     ansible.builtin.dnf:
       name: python3-firewall
       state: present

  - name: Open port on firewall
    ansible.posix.firewalld:
      service: docker-swarm
      permanent: yes
      state: enabled

  - name: Check if Swarm has already been Initialized
    command: docker node ls
    register: swarm_status
    ignore_errors: true

  - name: Initialize Docker Swarm
    command: docker swarm init --advertise-addr={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:2377
    when: swarm_status.rc != 0

  - name: Get the worker join-token
    command: docker swarm join-token --quiet worker
    register: worker_token

  - name: Show Worker Token
    debug: var=worker_token.stdout

- name: Join worker to the swarm cluster
  hosts: swarm_workers
  become: true
  gather_facts: False

  vars:
    token: "{{ hostvars[groups['swarm_manager'][0]]['worker_token'].stdout }}"
    master: "{{ hostvars[groups['swarm_manager'][0]]['ansible_default_ipv4']['address'] }}"
    
  tasks:
  - name: Add Workers to the Swarm
    command: docker swarm join --token {{ token }} {{ master }}:2377
    register: worker

  - name: Show Results
    debug: var=worker.stdout

  - name: Show Errors
    debug: var=worker.stderr