
- name: Iptables flush filter
  ansible.builtin.iptables:
    chain: INPUT
    flush: yes

- name: Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Allow ICMP
  ansible.builtin.iptables:
    chain: INPUT
    protocol: icmp
    jump: ACCEPT

- name: Allow TCP connections on multiple ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports: "{{ item }}"
    ctstate: NEW
    jump: ACCEPT
  loop: "{{ tcp_ports }}"

- name: Allow UDP on multiple ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    destination_ports: "{{ item }}"
    jump: ACCEPT
  loop: "{{ udp_ports }}"

- name: Reject all
  ansible.builtin.iptables:
    chain: INPUT
    protocol: all
    reject_with: icmp-host-prohibited
