- name: Install GlusterFS repository
  ansible.builtin.package:
    name: centos-release-gluster 
    state: present

- name: Install GlusterFS server
  ansible.builtin.package:
    name: glusterfs-server
    state: present

- name: Start service glusterfs
  ansible.builtin.service:
    name: glusterd
    enabled: yes
    state: started

- name: Creates directory
  file:
    path: "{{ brick_dir }}"
    state: directory

- name: Creates directory
  file:
    path: "{{ mount_dir }}"
    state: directory

- name: Give permissions for docker
  ansible.builtin.file:
    path: /mnt/docker-data
    owner: root
    group: docker
    mode: "770"
