- name: Get GlusterFS GPG key
  apt_key:
    url: https://download.gluster.org/pub/gluster/glusterfs/9/rsa.pub
    state: present

- name: Install software-properties-common
  ansible.builtin.apt:
    name: software-properties-common
    state: present

- name: Install GlusterFS repository
  apt_repository:
    repo: ppa:gluster/glusterfs-9

- name: Install GlusterFS server
  ansible.builtin.apt:
    name: glusterfs-server
    state: present

- name: Start service glusterfs
  ansible.builtin.service:
    name: glusterd
    enabled: yes
    state: started
    
- name: Install python binding for firewalld
  ansible.builtin.package:
    name: python3-firewall
    state: present

- name: Open port on firewall
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
  - 24007/tcp
  notify: reload firewall

- name: Creates directory
  file:
    path: "{{ brick_dir }}"
    state: directory

- name: Creates directory
  file:
    path: "{{ mount_dir }}"
    state: directory

- name: Give permissions for docker
  ansible.builtin.file:
    path: "{{ mount_dir }}"
    owner: root
    group: docker
    mode: "770"

- name: reload firewall
  systemd:
    name: firewalld
    state: reloaded
