- name: Get GlusterFS GPG key
  apt_key:
    url: https://download.gluster.org/pub/gluster/glusterfs/9/rsa.pub
    state: present

- name: Install software-properties-common
  ansible.builtin.apt:
    name: software-properties-common
    state: present

- name: Install GlusterFS repository
  apt_repository:
    repo: ppa:gluster/glusterfs-9

- name: Install GlusterFS server
  ansible.builtin.apt:
    name: glusterfs-server
    state: present

- name: Start service glusterfs
  ansible.builtin.service:
    name: glusterd
    enabled: yes
    state: started

- name: Creates directory
  file:
    path: "{{ brick_dir }}"
    state: directory

- name: Creates directory
  file:
    path: "{{ mount_dir }}"
    state: directory

- name: Give permissions for docker
  ansible.builtin.file:
    path: "{{ mount_dir }}"
    owner: root
    group: docker
    mode: "770"
