- name: Mount volume
  ansible.posix.mount:
    path: "{{ mount_dir }}"
    src: localhost:/volume01
    fstype: glusterfs
    opts: defaults,_netdev,backupvolfile-server=localhost
    boot: yes
    state: present

- name: Ensure Gluster volume is mounted.
  mount:
    name: "{{ mount_dir }}"
    src: localhost:/volume01
    fstype: glusterfs
    opts: "defaults,_netdev,noauto,x-systemd.automount"
    state: mounted
