- name: Probing the Nodes
  command: gluster peer probe {{ item }}
  with_items: "{{ groups['glusterfs'][1:] }}"

- name: Show cluster status
  command: gluster pool list
  register: gfs_status

- name: Show cluster status
  debug: var=gfs_status.stdout

- name: Check if the volume already exists
  command: gluster volume status volume01 detail
  register: volume_status
  ignore_errors: true

- name: Show volume status
  debug: var=volume_status.rc

- name: Create volume
  command: "gluster volume create volume01 replica 3 {{ hostvars[ groups['glusterfs'][0] ].ansible_hostname }}:{{ brick_dir }} {{ hostvars[ groups['glusterfs'][1] ].ansible_hostname }}:{{ brick_dir }} {{ hostvars[ groups['glusterfs'][2] ].ansible_hostname }}:{{ brick_dir }} force"
  when: volume_status.rc != 0

- name: Start the volume
  command: gluster volume start volume01
  when: volume_status.rc != 0
