- name: Probing the Nodes
  command: gluster peer probe {{ item }}
  with_items: "{{ groups['glusterfs'][1:] }}"

- name: Show cluster status
  command: gluster pool list

- name: Create one volume with 2 replica
  command: "gluster volume create volume01 replica {{ replica }}} {{ hostvars[ groups['glusterfs'][0] ].ansible_hostname }}:{{ brick_dir }} {{ hostvars[ groups['glusterfs'][1] ].ansible_hostname }}:{{ brick_dir }}"

- name: Start the volume
  command: gluster volume start volume01

- name: Mount volume
  ansible.posix.mount:
    path: "{{ mount_dir }}"
    src: localhost:/volume01
    fstype: glusterfs
    opts: defaults,_netdev,backupvolfile-server=localhost
    boot: yes
    state: present

- name: Ensure Gluster volume is mounted.
  mount:
    name: "{{ mount_dir }}"
    src: localhost:/volume01
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
