- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Running for {{ ansible_os_family }}
      include_tasks: tasks/{{ ansible_os_family }}.yml
    
    - name: adding {{ user }} to group docker
      user:
        name: {{ user }}
        groups: docker
        append: yes