- name: Install python binding for firewalld
  ansible.builtin.package:
    name: python3-firewall
    state: present

- name: Open port on firewall
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
  - 2376/tcp # secure Docker client communication
  - 2377/tcp # communication between the nodes and managers
  - 7946/tcp # communication among nodes 
  - 7946/udp # communication among nodes 
  - 4789/udp # overlay network traffic

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
