- name: Install python binding for firewalld
  ansible.builtin.package:
    name: python3-firewall
    state: present

- name: Open port on firewall
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop: "{{ ports }}"

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
